name: Generate Explain XKCD RSS Feed

on:
  schedule:
    - cron: "0 2 * * *"  # runs daily at 2am UTC
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper to generate feed
      run: |
        python generate_feed.py

    - name: Commit and push RSS feed
      env:
        GH_TOKEN: ${{ secrets.SECRET }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add explainxkcd.xml
        # Commit if there are changes; ignore if no changes
        git diff-index --quiet HEAD || git commit -m "Update Explain XKCD RSS feed"
        git push
